FROM rasa/rasa:latest-full

USER root
COPY server_requirements.txt /opt/requirements.txt

RUN apt-get update
RUN apt-get install nano
RUN source /opt/venv/bin/activate
RUN pip install -r /opt/requirements.txt

chmod -r

USER 1001