FROM python:3.7.7
COPY action_requirements.txt /opt/requirements.txt

RUN apt-get update
RUN apt-get install nano
RUN pip install -r /opt/requirements.txt

USER 1001

WORKDIR /app
CMD ["python", "-m", "rasa_sdk", "--actions", "actions.actions"]