version: '3'
services:
  rasa:
    image: rasa/rasa:latest-full
    container_name: rasa_server
    networks:
      - rasa
    ports:
      - 5005:5005
    volumes:
      - ./rasa-data/:/app/
    command:
      - run

  action_server:
    image: rasa/rasa-sdk:latest
    container_name: rasa_action_server
    ports:
      - 5055:5055
    volumes:
      - ./rasa-data/actions:/app/actions
    networks:
      - rasa

  duckling:
    image: rasa/duckling:latest
    networks:
      - rasa
    ports:
      - 8000:8000

networks:
  rasa: